on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 0' # weekly

jobs:
  QueryCIDRs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-go@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - run: pip install -r requirements.txt
      
      - run: go install github.com/j3ssie/sdlookup@latest

      - run: sudo apt update ; sudo apt install jq unzip ripgrep -y

      - run: wget -O ip-country-csv.zip "${{ secrets.IP2LOC_LINK }}" && unzip ip-country-csv.zip


      - name: filtering
        run: |
          rg -F '"'${{ secrets.HOSTNAME_FILTER }}'"' IP2LOCATION-LITE-DB1.CSV > filtered-ipdb.csv
          ./print_filtered_cidrs.py > filtered.cidrs

    
      - name: run queries
        run: for cidr in $(cat filtered.cidrs); do echo $cidr | sdlookup -json > $(echo $cidrs | tr / _).json ; done

      - name: upload reports
        uses: actions/upload-artifact@v4
        with:
          name: new-report
          path: ./*.json

      - name: gen txt report
        run: ls -l *json > report.txt

      - name: Commit and push results
        run: | 
          git config --global user.name 'techliberation'
          git config --global user.email '111632185+techliberation@users.noreply.github.com'
          git config --global branch.autoSetupMerge always
          git config --global core.mergeoptions --no-edit
          git config --global pull.rebase false

          git add *.txt || echo no report
          git commit -m "new output $(date)"
          git pull
          git push 


